# Generated by Django 4.1.7 on 2023-03-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_tag_alter_category_created_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
